import streamlit as st
import pandas as pd
import time
import random

# --- Mock Data from the Notebook ---
# This simulates the "uploaded" PDF and the "scraped" job description.
# In the real app, this would be dynamic.
SAMPLE_DATA = [
    {
        "candidate": "Ann Marshall",
        "role": "Game Developer",
        "resume_snippet": "Here's a professional resume for Ann Marshall: ... [Full Resume Content would be here] ... Strong technical skills in AI and ML. Experience with Unity and C#.",
        "decision": "Select",
        "reason": "Strong technical skills in AI and ML.",
        "job_desc": "Help us build the next-generation products as a Game Developer. detailed knowledge of AI required."
    },
    {
        "candidate": "Jason Jones",
        "role": "E-commerce Specialist",
        "resume_snippet": "Here's a professional resume for Jason Jones: ... [Full Resume Content] ... Managed online store operations.",
        "decision": "Reject",
        "reason": "Lacked leadership skills for a senior position.",
        "job_desc": "Be part of a passionate team at the forefront of E-commerce. We need a leader with 5+ years experience."
    },
    {
        "candidate": "Zachary Ward",
        "role": "AI Researcher",
        "resume_snippet": "Here's a sample resume for Zachary Ward: ... [Full Resume Content] ... Excellent full-stack development experience. PhD in Computer Science.",
        "decision": "Select",
        "reason": "Excellent full-stack development experience.",
        "job_desc": "If you're passionate about software engineering and AI research, join us."
    }
]

# --- Helper Functions (Simulating Backend Logic) ---

def mock_parse_resume(candidate_name):
    """Simulates parsing a PDF resume."""
    time.sleep(1) # Simulate processing time
    for data in SAMPLE_DATA:
        if data["candidate"] == candidate_name:
            return data["resume_snippet"]
    return "Resume not found."

def mock_scrape_job(url):
    """Simulates scraping a job description from a URL."""
    time.sleep(1.5) # Simulate network request
    # For PoC, we just return a random JD from our sample or a specific one based on input
    return SAMPLE_DATA[0]["job_desc"] if "game" in url.lower() else SAMPLE_DATA[1]["job_desc"]

def mock_predict_suitability(resume_text, job_text):
    """Simulates the ML prediction."""
    # Simple logic for PoC: random score or based on length
    score = random.randint(40, 95)
    decision = "Accepted" if score > 70 else "Rejected"
    return score, decision

def mock_tailor_resume(resume_text, job_text):
    """Simulates LLM rewriting the resume."""
    time.sleep(2)
    return f"**TAILORED RESUME**\n\n(Optimized for keywords in Job Description)\n\n{resume_text}\n\n*Added emphasis on Leadership and Python skills.*"

def mock_generate_cover_letter(candidate_name, role):
    """Simulates LLM generating a cover letter."""
    time.sleep(2)
    return f"""
    Dear Hiring Manager,

    I am writing to express my strong interest in the {role} position.
    Based on my experience as {candidate_name}, I believe I am a perfect fit...

    [Generated by Arbyte AI]
    """

# --- Streamlit UI ---

st.set_page_config(page_title="Arbyte", page_icon="🚀", layout="wide")

st.title("🚀 Arbyte")
st.markdown("#### Eliminate rejection fatigue. Tailor your resume, predict outcomes, and land the job.")

# Sidebar - User Input (Resume)
with st.sidebar:
    st.header("1. Upload Resume")
    # In real app: st.file_uploader("Upload PDF", type=["pdf"])
    selected_candidate = st.selectbox(
        "Select a Sample Candidate (PoC Mode)",
        [d["candidate"] for d in SAMPLE_DATA]
    )

    st.info(f"Loaded resume for: **{selected_candidate}**")

    if st.button("Reset Session"):
        st.session_state.clear()
        st.rerun()

# Main Content
col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("Resume Preview")
    resume_text = mock_parse_resume(selected_candidate)
    st.text_area("Extracted Text", resume_text, height=300)

with col2:
    st.subheader("2. Job Application")
    job_url = st.text_input("Paste Job Position URL (LinkedIn/JobStreet)", placeholder="https://www.linkedin.com/jobs/view/...")

    if job_url:
        if st.button("Analyze Job Compatibility"):
            with st.spinner("Scraping Job Description & Running ML Model..."):
                # 1. Scrape
                scraped_jd = mock_scrape_job(job_url)
                st.session_state['scraped_jd'] = scraped_jd

                # 2. Predict
                score, decision = mock_predict_suitability(resume_text, scraped_jd)
                st.session_state['score'] = score
                st.session_state['decision'] = decision
                st.session_state['analyzed'] = True

    # Display Results if analyzed
    if st.session_state.get('analyzed'):
        st.success("Analysis Complete!")

        with st.expander("View Scraped Job Description"):
            st.write(st.session_state['scraped_jd'])

        # Score Visualization
        score = st.session_state['score']
        st.write(f"### Predicted Suitability Score: {score}/100")
        st.progress(score / 100)

        if st.session_state['decision'] == "Accepted":
            st.markdown("### 🟢 Prediction: Likely to be Selected")
        else:
            st.markdown("### 🔴 Prediction: Risk of Rejection")
            st.warning("Recommendation: Use the tools below to improve your score.")

        st.divider()

        st.subheader("3. AI Assistance")
        c1, c2 = st.columns(2)

        with c1:
            if st.button("✨ Tailor Resume"):
                with st.spinner("Optimizing resume..."):
                    tailored = mock_tailor_resume(resume_text, st.session_state['scraped_jd'])
                    st.session_state['tailored_resume'] = tailored

        with c2:
            if st.button("📝 Generate Cover Letter"):
                with st.spinner("Writing cover letter..."):
                    # Find role from sample data for better mock
                    role = next(d['role'] for d in SAMPLE_DATA if d['candidate'] == selected_candidate)
                    cl = mock_generate_cover_letter(selected_candidate, role)
                    st.session_state['cover_letter'] = cl

# Display Generated Content
if 'tailored_resume' in st.session_state or 'cover_letter' in st.session_state:
    st.divider()
    tab1, tab2 = st.tabs(["Tailored Resume", "Cover Letter"])

    with tab1:
        if 'tailored_resume' in st.session_state:
            st.markdown(st.session_state['tailored_resume'])
        else:
            st.info("Click 'Tailor Resume' to generate.")

    with tab2:
        if 'cover_letter' in st.session_state:
            st.markdown(st.session_state['cover_letter'])
        else:
            st.info("Click 'Generate Cover Letter' to generate.")
